services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: survey_user
      POSTGRES_PASSWORD: survey_pass
      POSTGRES_DB: survey_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - .:/app                 # Mount source code
      - ./storage:/app/storage
#      - /app/tmp               # Allow binary output
    depends_on:
      - db
    env_file:
      - .env

volumes:
  pgdata:
