version: "3.8"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: survey_user
      POSTGRES_PASSWORD: survey_pass
      POSTGRES_DB: survey_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  pgdata:
