version: "3.9"

services:
  app1:
    build:
      context: ./app
      dockerfile: Dockerfile
      target: dev
    volumes:
      - ./app:/app
    command: ["air"]

  app2:
    build:
      context: ./app
      dockerfile: Dockerfile
      target: dev
    volumes:
      - ./app:/app
    command: ["air"]

  app3:
    build:
      context: ./app
      dockerfile: Dockerfile
      target: dev
    volumes:
      - ./app:/app
    command: ["air"]
